'use strict';
const ingredients=[['Спагетти',400,'г',80,552],['Бекон (гуанчале)',150,'г',80,617],['Яйца',4,'шт.',80,681],['Пармезан',100,'г',80,746],['Сливки 20%',100,'мл',470,552],['Чёрный перец',null,'по вкусу',470,617],['Соль',null,'по вкусу',470,681]];
const steps=[['Отварите пасту','Вскипятите подсоленную воду и отварите спагетти до состояния al dente (7–9 минут).',992,550],['Обжарьте бекон','Нарежьте бекон и обжарьте на среднем огне до золотистой корочки.',992,640],['Приготовьте соус','Взбейте яйца, добавьте тёртый пармезан, чёрный перец и немного сливок.',992,730],['Соедините и подавайте','Смешайте горячую пасту с беконом, добавьте соус, тщательно перемешайте. Подавайте сразу, посыпая пармезаном.',992,822]];
let portions=4,favorite=false,toastTimer;const completed=new Set();
try{favorite=localStorage.getItem('vkusno-favorite')==='true'}catch{}
function renderIngredients(){document.querySelectorAll('[data-portions]').forEach(el=>el.textContent=portions);document.querySelector('#ingredient-list').innerHTML=ingredients.map(([name,amount,unit,x,y])=>`<div class="ingredient"><span class="food-icon" aria-hidden="true" style="--x:${x};--y:${y}"></span><span class="ingredient-name">${name}</span><span class="amount">${amount===null?unit:`${Number((amount*portions/4).toFixed(1)).toLocaleString('ru-RU')} ${unit}`}</span></div>`).join('');document.querySelector('#minus').disabled=portions<=1;document.querySelector('#plus').disabled=portions>=20}
function renderSteps(){document.querySelector('#step-list').innerHTML=steps.map(([title,text,x,y],index)=>`<div class="step ${completed.has(index)?'done':''}"><button class="step-number" data-step="${index}" aria-label="Отметить шаг ${index+1}: ${title}" aria-pressed="${completed.has(index)}">${completed.has(index)?'✓':index+1}</button><span class="step-thumb" aria-hidden="true" style="--x:${x};--y:${y}"></span><div><h3>${title}</h3><p>${text}</p></div></div>`).join('');document.querySelector('#step-progress').textContent=completed.size?`${completed.size} из 4`:''}
function renderFavorite(){const button=document.querySelector('#favorite');button.setAttribute('aria-pressed',favorite);button.querySelector('span').textContent=favorite?'В избранном':'В избранное';button.setAttribute('aria-label',favorite?'Удалить из избранного':'Добавить в избранное');document.querySelector('#favorite-count').textContent=favorite?'1':''}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2500)}
function route(){const view=location.hash.slice(1)||'recipe';const isRecipe=view==='recipe';document.querySelector('#recipe-view').hidden=!isRecipe;document.querySelector('#catalog-view').hidden=isRecipe;const favorites=view==='favorites';const query=document.querySelector('#search-input').value.trim().toLocaleLowerCase('ru');document.querySelector('#catalog-title').textContent=favorites?'Избранное':query?'Результаты поиска':'Каталог рецептов';document.querySelector('#catalog-description').textContent=favorites?'Рецепты, к которым хочется возвращаться.':'Любимые блюда для уютных вечеров дома.';document.querySelector('#catalog-results').innerHTML=(favorites&&!favorite)?'<p class="empty">Здесь пока нет рецептов. Нажмите сердечко на рецепте, чтобы сохранить его.</p>':(!favorites&&query&&!('паста карбонара итальянская кухня спагетти бекон'.includes(query)))?'<p class="empty">Рецепт не найден. Попробуйте «паста» или «карбонара».</p>':'<a class="recipe-card" href="#recipe"><img src="assets/carbonara.jpg" alt="Паста карбонара"><div><h2>Паста Карбонара</h2><p>25 минут · Итальянская кухня</p></div></a>';document.title=isRecipe?'Паста Карбонара — Вкусно Дома':`${favorites?'Избранное':'Каталог рецептов'} — Вкусно Дома`}
document.querySelector('#minus').addEventListener('click',()=>{if(portions>1)portions--;renderIngredients()});document.querySelector('#plus').addEventListener('click',()=>{if(portions<20)portions++;renderIngredients()});
document.querySelector('#favorite').addEventListener('click',()=>{favorite=!favorite;try{localStorage.setItem('vkusno-favorite',favorite)}catch{}renderFavorite();toast(favorite?'Рецепт добавлен в избранное':'Рецепт удалён из избранного')});
document.querySelector('#step-list').addEventListener('click',event=>{const button=event.target.closest('[data-step]');if(!button)return;const step=Number(button.dataset.step);completed.has(step)?completed.delete(step):completed.add(step);renderSteps();if(completed.size===4)toast('Всё готово. Приятного аппетита!')});
document.querySelector('#search-form').addEventListener('submit',event=>{event.preventDefault();location.hash='catalog';route()});document.querySelector('#search-input').addEventListener('input',()=>{if(location.hash==='#catalog')route()});window.addEventListener('hashchange',()=>{route();window.scrollTo({top:0,behavior:'instant'})});renderIngredients();renderSteps();renderFavorite();route();
