'use strict';
const initialRecipe={id:'carbonara',title:'Паста Карбонара',description:'Нежная, сливочная паста с хрустящим беконом и ароматным пармезаном. Настоящая итальянская классика у вас дома!',minutes:25,portions:4,photo:'assets/carbonara.jpg',cuisine:'Итальянская',dishType:'Основные блюда',tags:['Итальянская кухня','Основные блюда','Быстро','Популярное'],ingredients:[['Спагетти',400,'г',80,552],['Бекон (гуанчале)',150,'г',80,617],['Яйца',4,'шт.',80,681],['Пармезан',100,'г',80,746],['Сливки 20%',100,'мл',470,552],['Чёрный перец',null,'по вкусу',470,617],['Соль',null,'по вкусу',470,681]],steps:[['Отварите пасту','Вскипятите подсоленную воду и отварите спагетти до состояния al dente (7–9 минут).'],['Обжарьте бекон','Нарежьте бекон и обжарьте на среднем огне до золотистой корочки.'],['Приготовьте соус','Взбейте яйца, добавьте тёртый пармезан, чёрный перец и немного сливок.'],['Соедините и подавайте','Смешайте горячую пасту с беконом, добавьте соус, тщательно перемешайте. Подавайте сразу, посыпая пармезаном.']]};
const $=selector=>document.querySelector(selector),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cuisines=['Итальянская','Русская','Грузинская','Украинская','Белорусская','Казахская','Узбекская','Армянская','Азербайджанская','Французская','Испанская','Греческая','Турецкая','Китайская','Японская','Корейская','Индийская','Тайская','Мексиканская','Американская','Другая'];
const dishTypes=['Основные блюда','Супы','Салаты','Закуски','Гарниры','Завтраки','Выпечка','Десерты','Соусы','Напитки','Заготовки'];
const speedLabel=minutes=>minutes<=30?'Быстро':minutes<=60?'Среднее время':'Долго';
const formatNumber=value=>Number(value.toFixed(3)).toLocaleString('ru-RU',{maximumFractionDigits:3});
function recipeTags(recipe){return [{text:recipe.cuisine?`${recipe.cuisine} кухня`:(recipe.tags||[]).find(t=>t.includes('кухня')),kind:'cuisine'},{text:recipe.dishType||(recipe.tags||[]).find(t=>dishTypes.includes(t)),kind:'dish-type'},{text:speedLabel(recipe.minutes),kind:'speed'},...((recipe.tags||[]).includes('Популярное')?[{text:'Популярное',kind:'popular'}]:[])].filter(tag=>tag.text)}
let addedRecipes=[];
try{const stored=JSON.parse(localStorage.getItem('vkusno-recipes')||'[]');if(Array.isArray(stored))addedRecipes=stored.filter(r=>r&&typeof r.id==='string'&&typeof r.title==='string'&&typeof r.description==='string'&&Number.isFinite(r.minutes)&&r.minutes>0&&Number.isFinite(r.portions)&&r.portions>=1&&r.portions<=20&&Array.isArray(r.ingredients)&&r.ingredients.length&&r.ingredients.every(i=>Array.isArray(i)&&typeof i[0]==='string'&&(i[1]===null||Number.isFinite(i[1]))&&typeof i[2]==='string')&&Array.isArray(r.steps)&&r.steps.length&&r.steps.every(s=>Array.isArray(s)&&s.every(t=>typeof t==='string')))}catch{}
const recipes=()=>[initialRecipe,...addedRecipes];let current=initialRecipe,portions=4,toastTimer;const completed=new Set();
function photoUrl(recipe){return typeof recipe.photo==='string'&&(recipe.photo==='assets/carbonara.jpg'||/^data:image\/(jpeg|png|webp);base64,/.test(recipe.photo))?recipe.photo:''}
function renderIngredients(){document.querySelectorAll('[data-portions]').forEach(el=>el.textContent=formatNumber(portions));$('#ingredient-list').innerHTML=current.ingredients.map(([name,amount,unit,x,y],index)=>`<div class="ingredient ${x===undefined?'text-ingredient':''}">${x===undefined?'':`<span class="food-icon" aria-hidden="true" style="--x:${Number(x)};--y:${Number(y)}"></span>`}<span class="ingredient-name">${escapeHtml(name)}</span><span class="amount">${amount===null?escapeHtml(unit):`<input class="ingredient-quantity" data-ingredient="${index}" aria-label="Количество: ${escapeHtml(name)}" title="Изменить количество и пересчитать рецепт" type="text" inputmode="decimal" value="${formatNumber(amount*portions/current.portions)}" maxlength="16"><span>${escapeHtml(unit)}</span>`}</span></div>`).join('');$('#minus').disabled=portions<=0.01;$('#plus').disabled=false}
function applyIngredientAmount(input,editing=false){if(!input||!input.matches('[data-ingredient]'))return;const base=current.ingredients[Number(input.dataset.ingredient)][1];const amount=Number(input.value.trim().replace(/\s/g,'').replace(',','.'));const nextPortions=amount/base*current.portions;if(!Number.isFinite(amount)||amount<=0||amount>1e9||base<=0||!Number.isFinite(nextPortions)||nextPortions<0.01){if(!editing){toast('Введите положительное количество для не менее 0,01 порции.');renderIngredients()}return}portions=nextPortions;if(editing){document.querySelectorAll('[data-portions]').forEach(el=>el.textContent=formatNumber(portions));document.querySelectorAll('[data-ingredient]').forEach(el=>{if(el!==input)el.value=formatNumber(current.ingredients[Number(el.dataset.ingredient)][1]*portions/current.portions)});$('#minus').disabled=portions<=0.01}else renderIngredients()}
$('#ingredient-list').addEventListener('input',event=>applyIngredientAmount(event.target,true));
$('#ingredient-list').addEventListener('change',event=>applyIngredientAmount(event.target));
$('#ingredient-list').addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.matches('[data-ingredient]')){event.preventDefault();applyIngredientAmount(event.target)}});
function renderSteps(){$('#step-list').innerHTML=current.steps.map(([title,text],index)=>`<div class="step ${completed.has(index)?'done':''}"><button class="step-number" data-step="${index}" aria-label="Отметить шаг ${index+1}: ${escapeHtml(title)}" aria-pressed="${completed.has(index)}">${completed.has(index)?'✓':index+1}</button><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></div></div>`).join('');$('#step-progress').textContent=completed.size?`${completed.size} из ${current.steps.length}`:''}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2500)}
function renderRecipe(){const photo=$('.photo>img'),url=photoUrl(current);photo.hidden=!url;if(url)photo.src=url;else photo.removeAttribute('src');photo.alt=current.title;$('.photo').classList.toggle('no-photo',!url);$('.hero').classList.toggle('without-photo',!url);$('#recipe-title').textContent=current.title;$('.description').textContent=current.description;$('#recipe-time').textContent=`${current.minutes} мин`;$('.tags').innerHTML=recipeTags(current).map(t=>`<span class="${t.kind}">${escapeHtml(t.text)}</span>`).join('');renderIngredients();renderSteps()}
function route(){const view=location.hash.slice(1)||'recipe';const id=view.startsWith('recipe/')?view.slice(7):'carbonara';const found=recipes().find(r=>r.id===id);const isRecipe=(view==='recipe'||view.startsWith('recipe/'))&&!!found;$('#recipe-view').hidden=!isRecipe;$('#catalog-view').hidden=isRecipe;if(isRecipe){if(current.id!==found.id){current=found;portions=current.portions;completed.clear()}renderRecipe();document.title=`${current.title} — Вкусно Дома`;return}const query=$('#search-input').value.trim().toLocaleLowerCase('ru');$('#catalog-title').textContent=query?'Результаты поиска':'Каталог рецептов';const matching=recipes().filter(r=>`${r.title} ${r.description} ${recipeTags(r).map(t=>t.text).join(' ')} ${r.ingredients.map(i=>i[0]).join(' ')}`.toLocaleLowerCase('ru').includes(query));$('#catalog-results').innerHTML=matching.length?matching.map(r=>`<a class="recipe-card" href="#recipe/${encodeURIComponent(r.id)}">${photoUrl(r)?`<img src="${escapeHtml(photoUrl(r))}" alt="${escapeHtml(r.title)}">`:''}<div><h2>${escapeHtml(r.title)}</h2><p>${r.minutes} минут · ${r.portions} порции</p></div></a>`).join(''):'<p class="empty">Рецепты не найдены. Попробуйте другое название или ингредиент.</p>';document.title='Каталог рецептов — Вкусно Дома'}
$('#minus').addEventListener('click',()=>{portions=Math.max(0.01,portions-1);renderIngredients()});$('#plus').addEventListener('click',()=>{portions+=1;renderIngredients()});
$('#step-list').addEventListener('click',event=>{const button=event.target.closest('[data-step]');if(!button)return;const step=Number(button.dataset.step);completed.has(step)?completed.delete(step):completed.add(step);renderSteps();if(completed.size===current.steps.length)toast('Всё готово. Приятного аппетита!')});
$('#search-form').addEventListener('submit',event=>{event.preventDefault();location.hash='catalog';route()});$('#search-input').addEventListener('input',()=>{if(location.hash==='#catalog')route()});$('.brand').addEventListener('click',()=>{$('#search-input').value='';if(location.hash==='#catalog')route()});window.addEventListener('hashchange',()=>{route();window.scrollTo({top:0,behavior:'instant'})});
function addIngredient(){const row=document.createElement('div');row.className='ingredient-fields';row.innerHTML='<input class="field-name" aria-label="Название ингредиента" placeholder="Ингредиент" maxlength="100" required><input class="field-amount" aria-label="Количество" type="number" min="0.1" max="100000" step="any" placeholder="Кол-во"><input class="field-unit" aria-label="Единица измерения" placeholder="г / мл / по вкусу" maxlength="40" required><button type="button" class="remove-row" aria-label="Удалить ингредиент">×</button>';row.querySelector('button').addEventListener('click',()=>{if($('#ingredient-fields').children.length>1)row.remove();else toast('Нужен хотя бы один ингредиент')});$('#ingredient-fields').append(row)}
function renumberSteps(){[...$('#step-fields').children].forEach((row,index)=>{row.querySelector('.form-step-number').textContent=`Шаг ${index+1}`;row.querySelector('.field-step-title').setAttribute('aria-label',`Заголовок шага ${index+1}`);row.querySelector('.field-step-description').setAttribute('aria-label',`Описание шага ${index+1}`);row.querySelector('.remove-row').setAttribute('aria-label',`Удалить шаг ${index+1}`)})}
function addStep(){const row=document.createElement('div');row.className='step-fields';row.innerHTML='<div class="form-step-heading"><strong class="form-step-number"></strong><button type="button" class="remove-row">×</button></div><label>Заголовок<input class="field-step-title" placeholder="Например, приготовьте соус" maxlength="150" required></label><label>Описание<textarea class="field-step-description" placeholder="Что нужно сделать на этом шаге" rows="3" maxlength="3000" required></textarea></label>';row.querySelector('.remove-row').addEventListener('click',()=>{if($('#step-fields').children.length>1){row.remove();renumberSteps()}else toast('Нужен хотя бы один шаг')});$('#step-fields').append(row);renumberSteps()}
for(const [name,options] of [['cuisine',cuisines],['dishType',dishTypes]])$(`[name="${name}"]`).insertAdjacentHTML('beforeend',options.map(value=>`<option value="${value}">${value}</option>`).join(''));
function updateFormSpeed(){const minutes=Number($('#recipe-minutes').value);$('#form-speed').textContent=minutes>0?speedLabel(minutes):'Укажите время'}
$('#recipe-minutes').addEventListener('input',updateFormSpeed);$('#add-step').addEventListener('click',addStep);
$('#add-recipe').addEventListener('click',()=>{$('#recipe-form').reset();$('#form-error').hidden=true;$('#ingredient-fields').replaceChildren();addIngredient();$('#step-fields').replaceChildren();addStep();updateFormSpeed();$('#recipe-dialog').showModal()});$('#add-ingredient').addEventListener('click',addIngredient);['#close-dialog','#cancel-dialog'].forEach(selector=>$(selector).addEventListener('click',()=>$('#recipe-dialog').close()));
$('#recipe-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,submit=form.querySelector('[type=submit]');$('#form-error').hidden=true;submit.disabled=true;try{const data=new FormData(form),title=String(data.get('title')).trim(),description=String(data.get('description')).trim(),minutes=Number(data.get('minutes')),basePortions=4,cuisine=String(data.get('cuisine')),dishType=String(data.get('dishType'));const ingredients=[...$('#ingredient-fields').children].map(row=>[row.querySelector('.field-name').value.trim(),row.querySelector('.field-amount').value===''?null:Number(row.querySelector('.field-amount').value),row.querySelector('.field-unit').value.trim()]);const steps=[...$('#step-fields').children].map(row=>[row.querySelector('.field-step-title').value.trim(),row.querySelector('.field-step-description').value.trim()]);if(!title||!description||!steps.length||steps.some(s=>!s[0]||!s[1])||!cuisines.includes(cuisine)||!dishTypes.includes(dishType)||ingredients.some(i=>!i[0]||!i[2]))throw Error('Заполните название, описание, параметры блюда, ингредиенты, заголовок и описание каждого шага.');let photo='';const file=data.get('photo');if(file.size){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Выберите фото в формате JPG, PNG или WebP.');if(file.size>1024*1024)throw Error('Фотография должна быть не больше 1 МБ.');photo=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Не удалось прочитать фото.'));reader.readAsDataURL(file)});await new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(Error('Не удалось открыть изображение. Выберите другое фото.'));img.src=photo})}const recipe={id:`recipe-${crypto.randomUUID()}`,title,description,minutes,portions:basePortions,photo,cuisine,dishType,tags:[`${cuisine} кухня`,dishType,speedLabel(minutes)],ingredients,steps};const next=[...addedRecipes,recipe];try{localStorage.setItem('vkusno-recipes',JSON.stringify(next))}catch{throw Error('Не удалось сохранить рецепт: хранилище браузера недоступно или заполнено. Попробуйте фото меньшего размера.')}addedRecipes=next;$('#recipe-dialog').close();$('#search-input').value='';route();toast('Рецепт добавлен в каталог')}catch(error){$('#form-error').textContent=error.message;$('#form-error').hidden=false}finally{submit.disabled=false}});
route();
