import {test} from 'node:test';
import assert from 'node:assert/strict';
import {handleRequest} from './recipe-api.mjs';
const env={ALLOWED_ORIGIN:'https://karoda1995.github.io',GITHUB_TOKEN:'test-server-token',AUTH_SECRET:'test-session-signing-secret',AUTHOR_PASSWORD:'test-author-password'};
const request=(path,body,token='',origin=env.ALLOWED_ORIGIN)=>new Request(`https://test.invalid${path}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});
const recipe={id:'recipe-00000000-0000-4000-8000-000000000000',title:'Test recipe',description:'Recipe description',minutes:25,portions:4,cuisine:'Русская',dishType:'Завтраки',tags:['Быстро'],photo:'',ingredients:[['Яйца',4,'шт.','eggs']],steps:[['Cook','Boil the eggs.']]};
async function login(){const response=await handleRequest(request('/auth',{password:env.AUTHOR_PASSWORD}),env);assert.equal(response.status,200);return (await response.json()).token}
test('anonymous save makes no GitHub requests',async()=>{let calls=0;const response=await handleRequest(request('/recipes',recipe),env,()=>{calls++;throw Error('unexpected')});assert.equal(response.status,401);assert.equal(calls,0)});
test('other origins cannot sign in',async()=>{const response=await handleRequest(request('/auth',{password:env.AUTHOR_PASSWORD},'','https://other.invalid'),env);assert.equal(response.status,403);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null)});
test('bad password is rejected',async()=>assert.equal((await handleRequest(request('/auth',{password:'incorrect'}),env)).status,401));
test('signed-in save writes the exact recipe to the fixed repo folder',async()=>{const token=await login();const calls=[];const response=await handleRequest(request('/recipes',recipe,token),env,async(url,options)=>{calls.push([url,options]);return options.method==='PUT'?Response.json({commit:{sha:'test-commit'}},{status:201}):new Response(null,{status:404})});assert.equal(response.status,201);assert.equal((await response.json()).saved,true);assert.equal(calls.length,2);assert.match(calls[1][0],/^https:\/\/api.github.com\/repos\/Karoda1995\/vkusno-doma\/contents\/data\/recipes\/recipe-/);const body=JSON.parse(calls[1][1].body);assert.deepEqual(JSON.parse(Buffer.from(body.content,'base64').toString()).recipes,[recipe]);assert.equal(body.branch,'main');assert.equal(response.headers.get('Cache-Control'),'no-store')});
test('retry after uncertain completion does not create a duplicate commit',async()=>{const token=await login();let calls=0;const content=Buffer.from(JSON.stringify({schemaVersion:1,recipes:[recipe]},null,2)).toString('base64');const response=await handleRequest(request('/recipes',recipe,token),env,async()=>{calls++;return Response.json({content})});assert.equal(response.status,200);assert.equal(calls,1)});
test('existing recipe with different content is never overwritten',async()=>{const token=await login();let calls=0;const response=await handleRequest(request('/recipes',recipe,token),env,async()=>{calls++;return Response.json({content:'different'})});assert.equal(response.status,409);assert.equal(calls,1)});
test('tampered session is rejected',async()=>{const token=await login();assert.equal((await handleRequest(request('/recipes',recipe,token+'x'),env)).status,401)});
test('invalid quantities and path traversal are rejected before GitHub',async()=>{const token=await login();for(const bad of [{...recipe,id:'../../file'},{...recipe,ingredients:[['Яйца',-1,'шт.','eggs']]}]){const response=await handleRequest(request('/recipes',bad,token),env,()=>{throw Error('unexpected')});assert.equal(response.status,400)}});
test('provider errors do not expose server secrets',async()=>{const token=await login();const response=await handleRequest(request('/recipes',recipe,token),env,()=>{throw Error(env.GITHUB_TOKEN)});assert.equal(response.status,502);assert.equal((await response.text()).includes(env.GITHUB_TOKEN),false)});
